### ISSUE TITLE
How to make bold some of the column headers?

### ISSUE THREAD

**Issue by juliohm** [ronisbr/PrettyTables.jl#1]
Hi @ronisbr, thanks for this very useful package. I am planning to add it as a dependency in one of my packages. I was wondering if it is possible to make bold some of the column headers? Say I have:

```julia
using DataFrames

df = DataFrame(a=[1,2,3], b=[4,5,6], c=[7,8,9])
```
How do I pretty print the table and make `b` and `c` bold for example? Alternatively, a feature that would be really nice to have is a highlight of the background so that we could highlight the whole column with a background column. In this example I would highlight the column `a` with some color and columns `b` and `c` with another.

**Comment by ronisbr** [comment]
Hi @juliohm 

In fact, this is not possible right now. The header `header_bold` is applied to all the header. What do you think about let this be a boolean or a vector of booleans. In case of the latter, than we applied each vector element to each header. Seems good?

With respect to the background, it should be easy, but the Julia function `printstyled` does not support it. I will see if I can submit a PR so that we can still use this function.

**Comment by ronisbr** [comment]
In fact, it would be much better to just use https://github.com/KristofferC/Crayons.jl

**Comment by ronisbr** [comment]
@juliohm 

I have a good solution (unfortunately a breaking one). Change everything related to styling to use Crayons.jl. However, this can only happen if the PR https://github.com/KristofferC/Crayons.jl/pull/25 is accepted.

The problem is: in its current state, Crayons.jl does not verify if the `IO` has support to colors. In this case, if we print the table to a file, then all the escape sequences will be also printed, which is not good. My PR transforms the printing behavior of Crayons.jl to something like we have in `printstyled`.

**Comment by ronisbr** [comment]
@juliohm 

I found a way to do this without the PR! Now, every styling is handled by Crayons. Hence, you can select the background. I also let the keyword `header_crayon` be a `Crayon` or a `Vector{Crayon}`. Then, you can have different styles for different headers!
