### ISSUE TITLE
roadmap towards 1.0 release

### ISSUE THREAD

**Issue by bkamins** [ronisbr/PrettyTables.jl#100]
@ronisbr - this is not something super crucial since display changes are considered non-breaking, but I wanted to check with you what is the general roadmap towards 1.0 release in PrettyTables.jl? (the point is that it would be ideal to have 1.0 release of DataFrames.jl depend only on packages that have 1.0 release themselves)

CC @nalimilan

**Comment by ronisbr** [comment]
Perfect! I released 0.10 waiting for bugs so that 1.0 can be tagged. Only one bug was found by @nalimilan, which was fixed in v0.10.1. The next released should be v0.11, with modification to LaTeX backend (and the color changed proposed previously).

Conclusion: there is nothing stopping me to release v1.0, because only Text backend would be considered stable.

I just have one proposal. This morning I have an absolutely amazing idea how can I drastically reduce the work in DataFrames to align floating point columns whereas allowing anyone using PrettyTables to have this functionality. However, I am not sure if this will work fine. Give me one week to analyze this. If I am right, maybe we can tag 1.0 with this modification, leaving the code in DataFrames much more simple.

**Comment by bkamins** [comment]
Thank you. There is no rush. DataFrames.jl will be tagged 1.0 no faster than in 3 months from now!

**Comment by ronisbr** [comment]
I think I'll have a big problem in a very near future. It seems that [Formatting.jl](https://github.com/JuliaIO/Formatting.jl) is not maintained anymore. We have a bug that make it not work in Julia v1.6. It was even fixed in `master` but no release was tagged. I opened an issue about it but got not response:

https://github.com/JuliaIO/Formatting.jl/issues/94

Suggestions? I need to find a workaround before v1.0.

**Comment by bkamins** [comment]
I have pinged @nalimilan as he is a member of JuliaIO (I hope he would find time to have a look at it as it seems everything ends up relying on him - @nalimilan - sorry for pinging you again and thank you for all your service).

**Comment by bkamins** [comment]
@ronisbr - how strongly does PrettyTables.jl depend on Formatting.jl? Maybe this dependency could be easily dropped?

**Comment by ronisbr** [comment]
> @ronisbr - how strongly does PrettyTables.jl depend on Formatting.jl? Maybe this dependency could be easily dropped?

Sorry, I totally missed this question. Formatting.jl is used in a predefined formatter to enable C-like number printings. It will not be good to remove this. I think there is new code in Julia so that we can call a function similar to C's `printf` without a macro. However, it will not work in Julia 1.0. Anyway, a new version of Formatting.jl was tagged and everything is fine now.

Btw, I just pushed a new experimental feature! We can now specify a regex to align the cells in a columns. Hence, all that code in DataFrames.jl to provide floating pointing alignment can now be replaced by just a new configuration option:

```julia
julia> matrix = [ i == 2 ? missing :
                  i == 5 ? nothing : (-1)^j*10.0^(-i+j) for i = 1:7, j = 1:7];

julia> pretty_table(matrix, column_alignment_regex = Dict(i => r"\." for i = 1:7))
┌───────────┬───────────┬─────────────┬─────────────┬───────────────┬───────────────┬───────────────┐
│    Col. 1 │    Col. 2 │      Col. 3 │      Col. 4 │        Col. 5 │        Col. 6 │        Col. 7 │
├───────────┼───────────┼─────────────┼─────────────┼───────────────┼───────────────┼───────────────┤
│ -1.0      │ 10.0      │ -100.0      │ 1000.0      │ -10000.0      │ 100000.0      │     -1.0e6    │
│   missing │   missing │     missing │     missing │       missing │       missing │       missing │
│ -0.01     │  0.1      │   -1.0      │   10.0      │   -100.0      │   1000.0      │ -10000.0      │
│ -0.001    │  0.01     │   -0.1      │    1.0      │    -10.0      │    100.0      │  -1000.0      │
│   nothing │   nothing │     nothing │     nothing │       nothing │       nothing │       nothing │
│ -1.0e-5   │  0.0001   │   -0.001    │    0.01     │     -0.1      │      1.0      │    -10.0      │
│ -1.0e-6   │  1.0e-5   │   -0.0001   │    0.001    │     -0.01     │      0.1      │     -1.0      │
└───────────┴───────────┴─────────────┴─────────────┴───────────────┴───────────────┴───────────────┘
```

We just need to fill the dictionary in `column_alignment_regex` with the columns that has floating pointing number. I will do some tests, tag a new version, and then update DataFrames.jl. The code will be much more simple and nothing will break.

**Comment by bkamins** [comment]
This is fantastic. Thank you! I understand you want to align columns that have `eltype` being a subtype of `Union{AbstractFloat, Missing, Nothing}` this way or do explicit check of values in the column?

**Comment by waldyrious** [comment]
@ronisbr in the table you posted above, wouldn't it make more sense for the `missing` and `nothing` entries to be aligned to the left of the anchor (which would typically be the decimal point, as your example shows), rather than to the right?

(And speaking of "anchor", maybe `alignment_anchor_regex` would be a better, more explicit parameter name than `column_alignment_regex`, WDYT?)

**Comment by ronisbr** [comment]
> This is fantastic. Thank you! I understand you want to align columns that have `eltype` being a subtype of `Union{AbstractFloat, Missing, Nothing}` this way or do explicit check of values in the column?

In PrettyTables, I do not have access to the column type. Here I am only passing a regex to create an anchor to align the strings. In DataFrame.jl, we can use this in the columns that have floats (together with Missing and Nothing), to accomplish the same alignment I implemented previously. The good side is that we will not need anymore to convert the columns to text again. The performance should be improved a lot!

> @ronisbr in the table you posted above, wouldn't it make more sense for the `missing` and `nothing` entries to be aligned to the left of the anchor (which would typically be the decimal point, as your example shows), rather than to the right? (Or even centered! 😄)

I did this to match the printing mechanism of floats in `Base`. However, we can add an option to select the default alignment with respect to the anchor if no regex match is found. This is a very good idea, thanks!

> (And speaking of "anchor", maybe `alignment_anchor_regex` would be a better, more explicit parameter name than `column_alignment_regex`, WDYT?)

I am terrible in selecting keyword names :D I really liked your suggestion. I will rename this keyword.

**Comment by waldyrious** [comment]
> I am terrible in selecting keyword names :D I really liked your suggestion. I will rename this keyword.

I'm glad that helped!

> Btw, what would be a nice name for selecting the alignment behavior if a match is not found? It should be a keyword that is a symbol receiving :l, :c, or :r.

Hmm, not sure I got that clearly. Maybe a bit more of context would help — can you show me a snippet of pseudocode (using a placeholder name) where it would appear/be used?

**Comment by ronisbr** [comment]
Good! `fallback_alignment_anchor`. Thanks :D

**Comment by ronisbr** [comment]
Done! Now we can define the fallback alignment whatever we want. We can even have different options for different columns:

```julia
julia> matrix = [ i == 2 ? missing :
                  i == 5 ? nothing : (-1)^j*10.0^(-i+j) for i = 1:7, j = 1:7];

julia> pretty_table(matrix,
                    alignment_anchor_regex = Dict(i => r"\." for i = 1:7),
                    fallback_alignment_anchor_override = Dict(2 => :c, 4 => :r, 5 => :l),
                    fallback_alignment_anchor = :r)
┌─────────────┬─────────┬─────────────┬────────────┬───────────────┬──────────┬────────────┐
│      Col. 1 │  Col. 2 │      Col. 3 │     Col. 4 │        Col. 5 │   Col. 6 │     Col. 7 │
├─────────────┼─────────┼─────────────┼────────────┼───────────────┼──────────┼────────────┤
│     -1.0    │ 10.0    │   -100.0    │   1000.0   │ -10000.0      │ 100000.0 │     -1.0e6 │
│ missing     │ missing │ missing     │ missing    │       missing │ missing  │ missing    │
│     -0.01   │  0.1    │     -1.0    │     10.0   │   -100.0      │   1000.0 │ -10000.0   │
│     -0.001  │  0.01   │     -0.1    │      1.0   │    -10.0      │    100.0 │  -1000.0   │
│ nothing     │ nothing │ nothing     │ nothing    │       nothing │ nothing  │ nothing    │
│     -1.0e-5 │  0.0001 │     -0.001  │      0.01  │     -0.1      │      1.0 │    -10.0   │
│     -1.0e-6 │  1.0e-5 │     -0.0001 │      0.001 │     -0.01     │      0.1 │     -1.0   │
└─────────────┴─────────┴─────────────┴────────────┴───────────────┴──────────┴────────────┘
```

**Comment by waldyrious** [comment]
> Good! `fallback_alignment_anchor`.

Glad you like it! I'm not sure adding the "anchor" helps here, though. In `alignment_anchor_regex`, the "anchor" bit refers to (in the specific example you provided with `"\."`) the decimal point. Conversely, if that doesn't match, what one falls back to is the alignment itself (left, right or center), not a default anchor (like, say, `","` or something else). So I would insist on just `fallback_alignment`. Hope that makes sense!

**Comment by ronisbr** [comment]
I understand your point, but `fallback_alignment` is just too generic. We have the column alignment in `alignment` and the cell alignment override in `cell_alignment`. This new keywords affects only if you are using regex to create anchors. Hence, `fallback_alignment_anchor` seems a good choice. Something like "the fallback alignment with respect to the anchors if a match is not found".

**Comment by waldyrious** [comment]
I see. In that case, maybe swapping the word order could improve things, since in English the last word in such expressions is typically the actual noun, and the previous words work as adjectives.

So instead of `fallback_alignment_anchor` (where `anchor` seems to be the main subject, which does not match the actual intent as we're providing a fallback alignment, not a fallback anchor), I'd suggest `alignment_anchor_fallback`, so that `fallback` is the main subject, with "alignment" (as in "fallback alignment") being implicit. How does that sound?

**Comment by ronisbr** [comment]
@waldyrious done! Now we pass a vector of `Regex` instead of a `Regex` and pretty tables finds the first match. Hence, if we need to align the decimal point or the beginning of the line of all columns, we can do `Dict(0 => [r"\.", r"^"])`. Of course this logic can be coded inside the regex, but it can be more complicated for more advanced cases.

**Comment by ronisbr** [comment]
@bkamins I just need more testing before tagging a new version with those features. If everything goes right, all that part to compute the float alignment in DataFrames will be removed. The only thing we should do is to find Float columns and add a pair `i => [r"\.", r"^"]` to the dict in `alignment_anchor_regex`. If I am right, then we will have no output changes in DataFrames.

**Comment by waldyrious** [comment]
> @waldyrious done!

[I see](https://github.com/ronisbr/PrettyTables.jl/commit/c8902bca67c87d4a3320c995a37bd5fc28ec33e2), thanks for reconsidering!

**Comment by bkamins** [comment]
This is excellent!

From DataFrames.jl perspective the next step after doing this would be HTML/LaTeX support (see e.g. https://discourse.julialang.org/t/dataframes-show-ignores-column-width-prints-everything/53327).

**Comment by ronisbr** [comment]
> From DataFrames.jl perspective the next step after doing this would be HTML/LaTeX support (see e.g. https://discourse.julialang.org/t/dataframes-show-ignores-column-width-prints-everything/53327).

Perfect! My suggestion is to tag 1.0 after finishing Text backend, and then focus on the other two.

**Comment by GlenHertz** [comment]
Congrats on the release.  I think this can be closed now.
