### ISSUE TITLE
PrettyTables 0.12.1 is causing Dataframes to go back down to v0.21.8 from v0.22.7

### ISSUE THREAD

**Issue by StevenSiew** [ronisbr/PrettyTables.jl#119]
When I upgrade PrettyTables

`(@v1.6) pkg> up
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Installed RecursiveArrayTools ─ v2.11.2
   Installed StructTypes ───────── v1.7.1
   Installed DiffEqBase ────────── v6.59.0
   Installed DelayDiffEq ───────── v5.29.2
   Installed Symbolics ─────────── v0.1.21
   Installed JLLWrappers ───────── v1.3.0
   Installed FileIO ────────────── v1.7.0
   Installed Preferences ───────── v1.2.1
   Installed PrettyTables ──────── v0.12.1
    Updating `~/.julia/environments/v1.6/Project.toml`
  [a93c6f00] ↓ DataFrames v0.22.7 ⇒ v0.21.8
  [08abe8d2] ↑ PrettyTables v0.11.1 ⇒ v0.12.1
`

**Comment by ronisbr** [comment]
Hi @StevenSiew 

Yes, sorry about that. The problem is that DataFrames.jl with support to PrettyTables.jl v0.12 has not been released yet. Hence, if you have PrettyTables.jl v0.12, you would be downgraded to the DataFrames version that does not require PrettyTables.jl.

You have two options:

1) Downgrade PrettyTables.jl to v0.11.
2) Use `DataFrames#main` branch.
