### ISSUE TITLE
Question: How to export html prettytable to file?

### ISSUE THREAD

**Issue by gitboy16** [ronisbr/PrettyTables.jl#127]
Hi,
Thank you for this nice package.
I just started using it.
I saw your post :
https://discourse.julialang.org/t/prettytables-jl-now-has-initial-support-for-html-output/30905

I was wondering how I can export a html pretty table to a file .html?
Thank you

**Comment by gitboy16** [comment]
Sorry I am stupid it was atthe end of the post.

**Comment by ronisbr** [comment]
Nice! I am happy it is being useful.

No problem! Feel free to ask anything :)

Just notice that the html backend may change before stabilizing the API.

**Comment by TheCedarPrince** [comment]
Hey @ronisbr , sorry to comment on an old dead issue, but seemed the most appropriate place to ask. Is there any way to save an HTML formatted table to an image (such as a png)? Currently I can save the table to an HTML or text file, but having the image be saved would be quite nice! Thanks for the awesome package and congrats on 2.0! :smile:

**Comment by ronisbr** [comment]
Hi @TheCedarPrince !

Thanks! I thought at the beginning to add this feature. However, I needed to add a lot of dependencies to PrettyTables. Hence, it would increase a lot the loading time of packages that depends on PrettyTables. The best way is to save the table into an HTML file and use some tool to do the conversion, like https://wkhtmltopdf.org

**Comment by TheCedarPrince** [comment]
That's a really great suggestion @ronisbr - I developed a straightforward workflow upon your idea that folks may be interested in to get the achieved result I want (could be a good companion package someday in Julia with Artifact magic). Here is the workflow for posterity:

Requirements:

- Imagemagick
- wkhtmltoimage

Steps:

1. Create a PrettyTable HTML file with table as follows:

```julia
using PrettyTables 

open("test.html", "w") do f
    pretty_table(
        f,
        rand(3, 3),
        header=(["Age Group", "White", " "], [" ", "Male Prev.", "Female Prev."]),
        backend=:html
    )
end
```

This will produce an HTML page like this:

![image](https://user-images.githubusercontent.com/29561456/189501028-47c05909-c036-4db9-8a61-929147dacefd.png)

Lots of empty space and no way to access that table! Let's fix that.

2. Extract the HTML table to an image file via wkhtmltoimage:

```sh
wkhtmltoimage test.html table.png
```

Which looks like this:

![test](https://user-images.githubusercontent.com/29561456/189501065-009b86ba-94dd-4276-abb6-c372fa395363.png)

Less white space but still not perfect. We can do better! 

3. Crop to table with imagemagick:

```sh
convert table.png -trim final.png
```

Which gives us this beautiful table ready for publication or otherwise. :) 

![trim](https://user-images.githubusercontent.com/29561456/189501100-def3e45f-1d3f-4be4-a79a-fe988066fc85.png)

**Comment by ronisbr** [comment]
Very good!
