### ISSUE TITLE
Image cells in text backend

### ISSUE THREAD

**Issue by lorenzoh** [ronisbr/PrettyTables.jl#142]
So I have a basic version of a `CustomTextCell` working that uses ImageInTerminal.jl to draw images inside a table with a configurable maximum size. It looks like this:

![image](https://user-images.githubusercontent.com/28812146/134333158-6ae6992a-0098-4108-aaaf-a8a2a7aa8ec5.png)

Is there interest in having this in PrettyTables.jl? If there is, I'll open a pull request.

One note is that this would require taking on a dependency on either ImageInTerminal.jl itself or Requires.jl. Let me know what you think.

**Comment by ronisbr** [comment]
Hi @lorenzoh !

This is a very nice usage of CustomTextCell API :)

We can add to PrettyTables.jl, but we must take care of some problems:

1. Does the load time of the package increase? In this case, I think it is better to add dependency of Requires.jl instead of ImageInTerminal.jl.
2. The custom cell supports cropping? Did you test with limited cell width and limited display size?
3. Is the time to print the first cell degraded?
