### ISSUE TITLE
Quote marks around Strings 

### ISSUE THREAD

**Issue by lbilli** [ronisbr/PrettyTables.jl#16]
After updating to DataFrames 0.19.0, strings are printed surrounded by escaped quote marks `\"`:
```julia
julia> df = DataFrame(:a => [1, 2], :b => ["A", "B"]);

julia> pretty_table(df)
┌───────┬────────┐
│     a │      b │
│ Int64 │ String │
├───────┼────────┤
│     1 │  \"A\" │
│     2 │  \"B\" │
└───────┴────────┘
```
For the time being, I'm able to get around this issue like this:
```julia
julia> pretty_table(df; formatter=Dict(0 => (v,i) -> v[1]))
┌───────┬────────┐
│     a │      b │
│ Int64 │ String │
├───────┼────────┤
│     1 │      A │
│     2 │      B │
└───────┴────────┘
```

**Comment by ronisbr** [comment]
hi @lbilli 

Thanks for reporting, I will try to analyze this tomorrow.

**Comment by ronisbr** [comment]
Done! Sorry for the delay, it was somewhat difficult to debug. It was caused by a "bug" (which I am not sure if it will be fixed) that was changing the behavior of DataFrames when `@views` is used. However, the usage of `@views` in the context of PrettyTables.jl was not necessary. I am tagging a new version, but if you use `master` it should be fixed by now:

```julia
julia> df = DataFrame(:a => [1, 2], :b => ["A", "B"]);

julia> pretty_table(df)
┌───────┬────────┐
│     a │      b │
│ Int64 │ String │
├───────┼────────┤
│     1 │      A │
│     2 │      B │
└───────┴────────┘
```
