### ISSUE TITLE
Transition to 2.0 and new keyword argument names

### ISSUE THREAD

**Issue by thchr** [ronisbr/PrettyTables.jl#178]
I was hoping it might be possible to allow both v1 and v2 of PrettyTables for a while, but I noticed that some of the new keyword arguments (e.g., `show_header`) don't work on v1. As a result, it is not possible to simply update new code to use the new keyword arguments without simultaneously dropping support for 1.0.

I wonder if it could be possible to tag a new, final release of the PrettyTables v1.x series, but with the new keyword argument names working? That way, downstream packages could allow both v1 and v2 PrettyTables for a while, which could help avoid compatibility conflicts.

**Comment by ronisbr** [comment]
In fact, I did the opposite! The old arguments will work in v1.3. Hence, for example, `noheader` was deprecated, but it works! Hence, if you are using v1, you do not need to change anything, because it will work. If you need to move to the new API, why you cannot bump PrettyTables version?

**Comment by thchr** [comment]
If I drop support for PrettyTables v1 in some package, but that package depends on another package that also depends on PrettyTables but has not yet moved to v2, then there will be a version conflict, no?

I.e., dropping v1 support immediately may not be so simple unless it is widely and concurrently done by other dependents og PrettyTables. Since there are so many dependents of PrettyTables this seems to be unlikely.
Won't the result then most likely be that the old keyword names have to stay in use in favor of the new names?

**Comment by ronisbr** [comment]
This kind of conflict always happen and it is caused by how Julia manages the session. Currently, we cannot use two versions of the same package in the same session.

PrettyTables.jl v2 is breaking. Hence, even supporting the new keywords in the old version, some behavior changed. For example, filters were removed, the HTML output changed a lot, etc. Thus, it is very difficult for a package to support concurrently v1 and v2. What I did was to make the transition v1 to v2 as smooth as possible. However, if a package you depend did not bump to v2, you need to ask the developer to do it. Otherwise, you cannot bump you package without conflicts.

**Comment by thchr** [comment]
Fair enough; I realize that two-way forward/backward compatibility can be too annoying to maintain. Thanks a bunch for the efforts to keep backward compatibility though.

I think we can close this now then.

**Comment by ronisbr** [comment]
Sorry about that! I tried as hard as possible to avoid a breaking release, but I couldn't. I know how annoying those updates can be.

Please, if you need any help upgrading the packages, feel free to ping me!
