### ISSUE TITLE
Planning to support HTML output?

### ISSUE THREAD

**Issue by juliohm** [ronisbr/PrettyTables.jl#2]
That would pretty much solve all the problems related to printing tables in Julia :+1:

**Comment by ronisbr** [comment]
Nice idea! I think I can change the structure to create an API so that we can have many different format types. However, I have no idea how difficult this would be and how much time it will take.

**Comment by FelipeLema** [comment]
[Pandas documentation on styling](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html) is a very good starting point.

**Comment by bkamins** [comment]
If you wanted to suport this it would be ideal if also LaTeX output were supported (IJulia typically expects both HTML and LaTeX to work properly when exporting a notebook to PDF).

**Comment by ronisbr** [comment]
Hi guys!

I finally had time to work on this. It is still a WIP, but I would like to have some feedback from you if possible. The code is in `master` branch. [Here](https://discourse.julialang.org/t/prettytables-jl-now-has-initial-support-for-html-output/30905) you can see a screenshot of a table being printed to a Jupyter notebook.

**Comment by FelipeLema** [comment]
I love the integration with ColorSchemes.jl.
Perhaps the `background` and `foreground` parameters could be converted inside `HTMLDecoration()`? it seems that it _must_ be passed as string right now.

**Comment by ronisbr** [comment]
Hi @FelipeLema 

I are 100% right. I have already done that. Now, inside `HTMLDecoration` you have `color` and `background`.

**Comment by aminya** [comment]
@ronisbr to fix https://github.com/ronisbr/PrettyTables.jl/issues/30 and https://github.com/ronisbr/PrettyTables.jl/issues/29, you should use an HTML processor backend instead of making up the text yourself.

I can help you use my [AcuteML.jl](https://github.com/aminya/AcuteML.jl), if you are interested.

**Comment by aminya** [comment]
I wrote a prototype of using AcuteML for PrettyTables here: https://gist.github.com/aminya/8938bf64b9239dd71f06d214246f0b05

**Comment by ronisbr** [comment]
Hi @aminya 

> @ronisbr to fix #30 and #29, you should use an HTML processor backend instead of making up the text yourself.
> 
> I can help you use my [AcuteML.jl](https://github.com/aminya/AcuteML.jl), if you are interested.

This is something I would like to avoid. Notice that the idea is to just print tables using HTML with basic features. I want to make this package as small as possible, since it can be used as a dependency for other packages. Right now, the load time is 0,19s and the load time of AcuteML is 0,13s. Thus, adding AcuteML as a dependency of PrettyTables would almost double to load time, which is not good.

Maybe if we, in the future, split the package into PrettyTablesHTML, PrettyTablesLaTeX, and so on to decrease the loading  time, then we can think about having an external processor.

**Comment by ronisbr** [comment]
In fact, I think we can close this bug! :)

The HTML back-end is working (it can be polished, but we have an initial version).

@juliohm if you think the code is not exactly what you would expect, then, please, feel free to reopen this bug!

**Comment by aminya** [comment]
> Maybe if we, in the future, split the package into PrettyTablesHTML, PrettyTablesLaTeX, and so on to decrease the loading time, then we can think about having an external processor.

Hi @ronisbr,
So probably we should do this sooner. 
It takes time to wait for this kind of features:
https://github.com/JuliaLang/Pkg.jl/issues/1251

**Comment by waldyrious** [comment]
> @juliohm if you think the code is not exactly what you would expect, then, please, feel free to reopen this bug!

Just FYI, if I recall correctly, only the repo owner or manually added collaborators can reopen issues that have been closed. Not even the issue author can do so. 🤷‍

**Comment by ronisbr** [comment]
Oh! Good point.

So if anyone thinks this has not been fixed yet, then just let me know and I will reopen it :)
