### ISSUE TITLE
OrderedDict ?

### ISSUE THREAD

**Issue by LaurentPlagne** [ronisbr/PrettyTables.jl#23]
Hi,
would be nice to be able to use PrettyTables with OrderedDict (I would like to pretty print a dictionary whith the insertion order...)

**Comment by ronisbr** [comment]
Hi @LaurentPlagne 

Do you mean `OrderedDict` from DataStructures.jl? If this is the case, I am afraid that it is not a good move. AFAIK, in order to natively support printing structures defined in other packages, PrettyTables.jl must add those packages as dependencies. In this case, loading DataStructures.jl (which is a very big package) takes almost twice the time needed to load PrettyTables.jl:

```julia
julia> @time using DataStructures
  0.245166 seconds (283.70 k allocations: 16.532 MiB, 5.28% gc time)

julia> @time using PrettyTables
  0.147966 seconds (214.00 k allocations: 11.887 MiB, 2.62% gc time)
```

Hence, if I do this, then PrettyTables.jl load time will be almost 3x slower.

The support we have of printing DataFrames is because it complies with Tables.jl API, which OrderedDict does not. Thus, I think we have only two solutions:

1. Ask if DataStructures.jl maintainers can make OrderedDict comply with Tables.jl API; or
2. Convert OrderedDict to Dict before printing with the `sortkeys = true` keyword:

```julia
julia> ordered_dict = OrderedDict(3 => "a", 2 => "b", 1 => "c");

julia> pretty_table(Dict(ordered_dict), sortkeys = true)
┌───────┬────────┐
│  Keys │ Values │
│ Int64 │ String │
├───────┼────────┤
│     1 │      c │
│     2 │      b │
│     3 │      a │
└───────┴────────┘
```

P.S.: If anyone has any idea how can we do this without adding DataStructures.jl as dependencies, please let me know!

**Comment by ronisbr** [comment]
In fact, it just occurred to me that you can make `OrderedDicts` comply with Tables.jl API:

```julia
using DataStructures
using PrettyTables
using Tables

Tables.istable(::OrderedDict) = true
Tables.columns(d::OrderedDict) = hcat( vcat(keys(d)...), vcat(values(d)...) )
Tables.schema(d::OrderedDict) = (names = ["Keys","Values"],
                                 types = [eltype(d.keys), eltype(d.vals)])

ordered_dict = OrderedDict(3 => "b", 2 => "c", 1 => "d", 0 => "a")

@pt ordered_dict
```

which leads to:

```
┌───────┬────────┐
│  Keys │ Values │
│ Int64 │ String │
├───────┼────────┤
│     3 │      b │
│     2 │      c │
│     1 │      d │
│     0 │      a │
└───────┴────────┘
```

**Comment by LaurentPlagne** [comment]
Super cool !
Thank you very much
Laurent
