### ISSUE TITLE
Tables with some emojis are printed with uneven layout

### ISSUE THREAD

**Issue by sumiya11** [ronisbr/PrettyTables.jl#252]
For example, see the screenshot:

<img width="273" alt="image" src="https://github.com/user-attachments/assets/8188a195-35ff-492f-9778-327bb250ac56">

**Comment by ronisbr** [comment]
Hi @sumiya11 !

That's probably the UTF-8 support in your terminal / font. We rely on the function `textwidth` to compute how many display characters an UTF-8 character use to be rendered. This function seems to work well for many cases. However, if your terminal does not use the correct width during the rendering, it will be off and there is nothing we can do about it :(

Notice that the missing space for the correct alignment does not seem to be an entire character. Hence, I really think that the problem is the rendering process of your terminal + font.

This problem will occur even if you print this character on your terminal even outside Julia. Hence, unfortunately there is nothing we can do from PrettyTables.jl side :(

**Comment by sumiya11** [comment]
Thanks for the answer! I see.

Notes:
- The issue is present in all terminals I tried: Windows terminal, Jypyter Lab terminal, Github CI (https://github.com/sumiya11/Groebner.jl/actions/runs/11951526397/job/33315323221#step:5:431)
- The issue seems present in Python as well, on Windows at least, which may confirm your guess:

```
>>> "{:<10}|".format("hi ☺️  ")
'hi ☺️     |'
>>> "{:<10}|".format("hi 👿  ")
'hi 👿      |'
```

**Comment by ronisbr** [comment]
Yes... some of the emojis are not handled correctly unfortunately. This problem also happens to the flags in most of the cases.
