### ISSUE TITLE
Add title option

### ISSUE THREAD

**Issue by DhruvaSambrani** [ronisbr/PrettyTables.jl#32]
Add title option for tables, especially in HTML and Latex.

**Comment by ronisbr** [comment]
Hi @DhruvaSambrani ,

Can you please provide an example? What do you mean by title in tables?

**Comment by DhruvaSambrani** [comment]
So something like the table metadata, for example, a table of readings of potential vs current should have a title or table name called that. Then people can use it to name their tables according to whatever scheme they use. It can also be used to number tables as Table 3.6 for example in a large document

**Comment by DhruvaSambrani** [comment]
In repl, you could just print another line, but yeah

**Comment by ronisbr** [comment]
In LaTeX, the idea is to generate a `tabular` and not a `table`. You create the `table` env. and then include the LaTeX table created by PrettyTables.jl inside this env. The same thing can be done with HTML. Thus, I think this is something that should not be in this package.

Can you please provide and example of how do you expect this to work in text, html, and LateX environments?

**Comment by DhruvaSambrani** [comment]
Ohk makes sense then.

Basically I was expecting it to work like Plots having a "title", but if you think it shouldn't be a part of the package as you said above, you can close this issue

**Comment by ronisbr** [comment]
No! I still not sure :) I just want some example of usage, maybe I am overlooking something nice!

**Comment by DhruvaSambrani** [comment]
Oh ok. 
So consider that I'm doing a survey which has multiple questions and I need to generate the results as a set of tables to display with my analysis. In the text of the analysis, I would refer to tables by some code like "Table 3.68". The "title" of the table would then be "Table 3.68 - Responses to Section 6" for example. 
If this is part of the framework itself, then I could simply add a title to each table.
- in html, you then don't need to then format a title to go under your table
- in text, you could conveniently call one function that would nicely print the table with all table metadata. Else, I'd have to call a print(IO, "Title") before prettify_table(...)
- I don't really use LaTex, so I'm not sure whether one should add it or not.

Thanks for your time

**Comment by ronisbr** [comment]
Hum interesting! Maybe we can add some kind of `metadata` as you pointed out and, if available, change how we print the table in each backend. Nice suggestions, thanks! Let me see what can I do :)

**Comment by tlienart** [comment]
- For text / REPL precede table with `"$title\n\n"` (in bold)
- For HTML use table caption `<caption>$title</caption>` in the `<table>...</table>` env
- For LaTeX use caption `\caption{...}` in the tabular environment

even better if you can attach custom style to title but I would understand if that's a bit annoying

**Comment by ronisbr** [comment]
Excellent! I will use these instructions. They seem very good :)

**Comment by ronisbr** [comment]
Hi @tlienart and @DhruvaSambrani 

I finally had some time to do this! I followed the ideia of @tlienart for each backend. The only minor problem was that I need to wrap the LaTeX table in a `table` environment if `tabular` is used. Otherwise the caption does not work AFAIK.

For the text backend, we have some options. We can align the title, set the title width to be the screen size of table size, and we can also wrap long titles:

<img width="646" alt="Captura de Tela 2020-08-12 às 15 59 45" src="https://user-images.githubusercontent.com/1068295/90056440-426f4080-dcb5-11ea-996b-2983dbba8c49.png">

<img width="647" alt="Captura de Tela 2020-08-12 às 16 00 20" src="https://user-images.githubusercontent.com/1068295/90056445-44390400-dcb5-11ea-873c-3b9b8e73c6aa.png">

<img width="647" alt="Captura de Tela 2020-08-12 às 16 00 34" src="https://user-images.githubusercontent.com/1068295/90056461-49964e80-dcb5-11ea-91fd-21f7c581cd5f.png">

Can you please test it for me?

**Comment by tlienart** [comment]
Lgtm, small thought: you might want to add a kw `caption` and `caption_alignment` which would do the identical thing (so if you specify one it's the same as the other and if both are given one takes precedence). Just semantics I guess.

Thanks for this!

**Comment by ronisbr** [comment]
Hi @tlienart !

I think I did not understand. What will be the difference of this `caption` to the `title`?

**Comment by tlienart** [comment]
no difference, one would be an alias for the other (it's just that depending on what the user wants they may want to call it caption or title)

```
function pretty_table(args...; title="", caption=title, kwargs...)
    if !isempty(caption) && isempty(title)
        title = caption
    end
    # do stuff with title
end
```

allows to call with either `caption` or `title` kw and have the identical effect while using title w priority

**Comment by waldyrious** [comment]
FWIW, I understand a caption to be a (potentially) longer description of an item that appears below it, in normal size or slightly smaller, and a title as a name that is shown above it, typically shown in larger or otherwise emphasized font. In HTML, a caption would be usable as alt text, so that screen readers could describe the item for that can't present the visual form of the item. This may be another reason not to treat these as synonyms.

**Comment by ronisbr** [comment]
> FWIW, I understand a caption to be a (potentially) longer description of an item that appears below it, in normal size or slightly smaller, and a title as a name that is shown above it, typically shown in larger or otherwise emphasized font. In HTML, a caption would be usable as alt text, so that screen readers could describe the item for that can't present the visual form of the item. This may be another reason not to treat these as synonyms.

Hum, I think we should only use `title` to avoid confusion.

**Comment by nathanrboyer** [comment]
It looks like the `title` keyword is not longer implemented. Is there a different way that table titles are currently handled? I would just like a way to center some text above the table.

**Comment by ronisbr** [comment]
@nathanrboyer sorry, this is my fault. We are in a process to make PrettyTables.jl the default printing system for text in DataFrames.jl. In this case, I am saving the v1.0 when everything I need is implemented. Hence, the `title` is not yet available as a released version.

If you want to use it right now, you must use `master` instead of the release version. You can do this by:

```julia
julia> using Pkg

julia> Pkg.dev("PrettyTables")
```

<img width="1113" alt="Captura de Tela 2020-10-28 às 12 24 48" src="https://user-images.githubusercontent.com/1068295/97457501-9387eb80-1918-11eb-88b6-10d5fd14d69d.png">

**Comment by nathanrboyer** [comment]
Okay, no problem. I look forward to that very much!
